Adding getRawFile for repo
owenvoke/gitea-php pull request #6
Opened 2024-09-04 13:16 UTC by timdiels1

The API also allows to get raw file contents but the package did not include this. I've added this so the package allows to get raw file contents.

- [x] I have read the **[CONTRIBUTING](https://github.com/owenvoke/gitea-php/blob/main/.github/CONTRIBUTING.md)** document.

2024-09-04 13:30 UTC, owenvoke requested changes
LGTM, but would you be able to add a basic test to the [`tests/Api/RepoTest.php`](https://github.com/owenvoke/gitea-php/blob/main/tests/Api/RepoTest.php) file?

2025-07-03 20:38 UTC, timdiels1 commented
Hi Owenvoke, thanks for the reply and sorry for the really late reply from me. I finally got back to the project. I added a test, but not sure if it works, I made it out of my head. Sorry no idea at this moment how to test it locally.

2025-07-08 10:46 UTC, owenvoke reviewed
No worries, thanks for updating. 🙂 One change, and then happy to merge this. 👍🏻

2025-07-08 10:46 UTC, owenvoke commented on tests/Api/RepoTest.php
> +});
I've tested these changes to your test locally and it's working. 👍🏻
```suggestion
it("should fetch a raw file's data", function () {
    $expectedResponse = '# Gitea PHP';

    $api = $this->getApiMock();
    $api->expects($this->once())
        ->method('get')
        ->with('/repos/owenvoke/gitea-php/raw/README.md')
        ->willReturn($expectedResponse);

    expect($api->getRawFile('owenvoke', 'gitea-php', 'README.md'))->toBe($expectedResponse);
});
```

2025-07-08 10:48 UTC, owenvoke commented on tests/Api/RepoTest.php
> +});
Actually, I'll merge and then apply the changes separately. 👍🏻 Thanks for your work on this.

2025-07-08 10:49 UTC, merged